#!/bin/bash
#$ -N si_struc_min
#$ -cwd
#$ -pe mpi 16
#$ -S /bin/bash
#$ -q all.q
#$ -e job.err
#$ -o job.out

echo start_time:$(date)
# load compile tool chain
module load compilers/intel_16.0.3
module load apps/vasp_5.3.5
 
VASP=vasp-std
 
MPIRUN=mpiexec.hydra

echo The location of vasp is $(which $VASP)
echo The location of mpi is $(which mpiexec.hydra)

$MPIRUN $VASP > job.log

echo stop_time:$(date)
